import type { Locale } from "@/types/i18n";
import type { JobCategory, JobPreview, Region } from "@/types/jobs";

export const categoryLabels: Record<JobCategory, Record<Locale, string>> = {
  loaders: {
    hy: "բանվորներ",
    ru: "Грузчики",
    en: "Loaders",
    fa: "باربران",
    hi: "लोडर",
  },
  moving: {
    hy: "Տեղափոխություն",
    ru: "Переезд",
    en: "Moving",
    fa: "اسباب‌کشی",
    hi: "शिफ्टिंग",
  },
  loading: {
    hy: "բեռնաբեռնման ծառայություններ",
    ru: "Погрузка",
    en: "Loading",
    fa: "بارگیری",
    hi: "लोडिंग",
  },
  "home-help": {
    hy: "օգնություն տան գործերում",
    ru: "Помощь по дому",
    en: "Home help",
    fa: "کمک خانگی",
    hi: "घरेलू मदद",
  },
  cleaning: {
    hy: "Մաքրում",
    ru: "Уборка",
    en: "Cleaning",
    fa: "نظافت",
    hi: "सफ़ाई",
  },
  repair: {
    hy: "Վերանորոգում",
    ru: "Ремонт",
    en: "Repair",
    fa: "تعمیر",
    hi: "मरम्मत",
  },
  delivery: {
    hy: "Առաքում",
    ru: "Доставка",
    en: "Delivery",
    fa: "تحویل",
    hi: "डिलीवरी",
  },
  other: {
    hy: "Այլ",
    ru: "Другое",
    en: "Other",
    fa: "سایر",
    hi: "अन्य",
  },
};

export const regionLabels: Record<Region, Record<Locale, string>> = {
  yerevan: {
    hy: "Երևան",
    ru: "Ереван",
    en: "Yerevan",
    fa: "ایروان",
    hi: "येरेवान",
  },
  aragatsotn: {
    hy: "Արագածոտն",
    ru: "Арагацотн",
    en: "Aragatsotn",
    fa: "آراگاتسوتن",
    hi: "अरागतसोत्न",
  },
  ararat: {
    hy: "Արարատ",
    ru: "Арарат",
    en: "Ararat",
    fa: "آرارات",
    hi: "अरारात",
  },
  armavir: {
    hy: "Արմավիր",
    ru: "Армавир",
    en: "Armavir",
    fa: "آرماویر",
    hi: "अर्माविर",
  },
  gegharkunik: {
    hy: "Գեղարքունիք",
    ru: "Гегаркуник",
    en: "Gegharkunik",
    fa: "گهغارکونیک",
    hi: "गेघारकुनिक",
  },
  kotayk: {
    hy: "Կոտայք",
    ru: "Котайк",
    en: "Kotayk",
    fa: "کوتایک",
    hi: "कोटाय्क",
  },
  lori: {
    hy: "Լոռի",
    ru: "Лори",
    en: "Lori",
    fa: "لوری",
    hi: "लोरी",
  },
  shirak: {
    hy: "Շիրակ",
    ru: "Ширак",
    en: "Shirak",
    fa: "شیراک",
    hi: "शिराक",
  },
  syunik: {
    hy: "Սյունիք",
    ru: "Сюник",
    en: "Syunik",
    fa: "سیونیک",
    hi: "स्यूनिक",
  },
  tavush: {
    hy: "Տավուշ",
    ru: "Тавуш",
    en: "Tavush",
    fa: "تاووش",
    hi: "तावुश",
  },
  "vayots-dzor": {
    hy: "Վայոց Ձոր",
    ru: "Вайоцдзор",
    en: "Vayots Dzor",
    fa: "وایوتس‌جور",
    hi: "वायोत्स ज़ोर",
  },
};

export const demoJobs: JobPreview[] = [
  {
    id: "job-1",
    title: {
      hy: "Պետք են 2 բեռնիչ սառնարանը բարձրացնելու համար",
      ru: "Нужны 2 грузчика поднять холодильник",
      en: "Need 2 loaders to carry a refrigerator upstairs",
      fa: "به ۲ باربر برای بردن یخچال به طبقه بالا نیاز است",
      hi: "फ़्रिज ऊपर ले जाने के लिए २ लोडर चाहिए",
    },
    category: "loaders",
    price: "10 000 AMD",
    region: "yerevan",
    address: {
      hy: "Աջափնյակ, Բաշինջաղյան փողոց",
      ru: "Ачапняк, улица Башинджагяна",
      en: "Ajapnyak, Bashinjaghyan Street",
      fa: "آجاپنیاک، خیابان باشینجاغیان",
      hi: "अजापन्याक, बाशिनजाघ्यान सड़क",
    },
    publishedAt: {
      hy: "10 րոպե առաջ",
      ru: "10 минут назад",
      en: "10 minutes ago",
      fa: "۱۰ دقیقه پیش",
      hi: "१० मिनट पहले",
    },
    urgent: true,
  },
  {
    id: "job-2",
    title: {
      hy: "Անհրաժեշտ է արագ մաքրում փոքր բնակարանում",
      ru: "Нужна быстрая уборка в небольшой квартире",
      en: "Need a quick cleaning for a small apartment",
      fa: "به نظافت سریع در آپارتمان کوچک نیاز است",
      hi: "छोटे अपार्टमेंट में तेज़ सफ़ाई चाहिए",
    },
    category: "cleaning",
    price: "8 000 AMD",
    region: "kotayk",
    address: {
      hy: "Աբովյան, Բարեկամության փողոց",
      ru: "Абовян, улица Барекамутян",
      en: "Abovyan, Barekamutyan Street",
      fa: "آبوویان، خیابان بارکاموتیان",
      hi: "अबोव्यान, बरेकामुतयान सड़क",
    },
    publishedAt: {
      hy: "25 րոպե առաջ",
      ru: "25 минут назад",
      en: "25 minutes ago",
      fa: "۲۵ دقیقه پیش",
      hi: "२५ मिनट पहले",
    },
    urgent: false,
  },
  {
    id: "job-3",
    title: {
      hy: "Փնտրում եմ մարդ երեկոյան արագ առաքման համար",
      ru: "Ищу человека для срочной вечерней доставки",
      en: "Looking for someone for an urgent evening delivery",
      fa: "برای تحویل فوری عصر به کسی نیاز دارم",
      hi: "शाम की ज़रूरी डिलीवरी के लिए किसी की तलाश है",
    },
    category: "delivery",
    price: "Договорная",
    region: "armavir",
    address: {
      hy: "Արմավիր, Կենտրոն",
      ru: "Армавир, центр",
      en: "Armavir, city center",
      fa: "آرماویر، مرکز شهر",
      hi: "अर्माविर, शहर केंद्र",
    },
    publishedAt: {
      hy: "43 րոպե առաջ",
      ru: "43 минуты назад",
      en: "43 minutes ago",
      fa: "۴۳ دقیقه پیش",
      hi: "४३ मिनट पहले",
    },
    urgent: true,
  },
];
